### ISSUE TITLE
How to rebuild PyTorch in l4t-pytorch Jetpack4.6.1 container 

### ISSUE THREAD

**Issue by yinfan98** [dusty-nv/jetson-containers#344]
@dusty-nv Hi, I need Python 3.8 in Jetpack4.6.1 l4t-pytorch docker. 
> only see Python 3.6 - [torch-1.10.0-cp36-cp36m-linux_aarch64.whl](https://nvidia.box.com/shared/static/fjtbno0vpo676a25cgvuqc1wty0fkkg6.whl) at PyTorch for Jetson

How can I rebuild the PyTorch ?
Thanks

**Comment by dusty-nv** [comment]
Hi @yinfan98, you can follow the same procedure as in this dockerfile that builds pytorch wheels:

https://github.com/dusty-nv/jetson-containers/blob/master/packages/pytorch/Dockerfile.builder

however, install/use `python3.8` instead of normal `python3`

also you may need to apply some patches to the source for older versions of PyTorch, you can find them under the `Build from Source` section of this thread:   https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048

**Comment by yinfan98** [comment]
Thanks！
