### ISSUE TITLE
Mounted directory into the container does not include any files it seems empty.

### ISSUE THREAD

**Issue by MuhammedRishdhi** [dusty-nv/jetson-containers#51]

**Comment by dusty-nv** [comment]
Which mounted directory?   If you check it outside the container, does it have files?
________________________________

**Comment by MuhammedRishdhi123** [comment]
Yes, the directory had the files outside the container. However when I changed the path from sudo docker run -it --rm --runtime nvidia --network host -v /home/user/project:/location/in/container nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 to sudo docker run -it --rm --runtime nvidia --network host -v $HOME/project:/root/project nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 the files were mounted to the docker container. So I think the error occurred due to path.
